# Makefile - General Makefile for build
#

# include gerneral Makefile configuration file
include ../Makefile.inc

# execute file list
EXE = clnt

all : ${EXE}

clean : 
	${RM} *.o ${EXE}

showall :
	@ echo ${EXE}

${EXE} :
